import { REC_OPTIONS } from './recOptions.js';

export const fantasy = {
  label: 'Fantasy & sci-fi',
  categories: [
    { id: 'WB', title: 'World & systems', weight: 0.20, question: 'How immersive was the world, magic, or tech?', lowLabel: 'Thin, inconsistent', highLabel: 'Fully realized', feels: { 0: 'Illogical, derivative, or full of plot-hole-inducing magic/tech rules.', 1: 'Shallow world-building that felt more like a stage backdrop than a setting.', 2: 'Familiar genre tropes with a few interesting lore details scattered in.', 3: 'Immersive setting with coherent rules and believable scope.', 4: 'Richly detailed world-building that felt expansive and vibrant.', 5: 'Brilliantly constructed world and lore that I was fully immersed in.' } },
    { id: 'CH', title: 'Characters', weight: 0.15, question: 'How did the characters land for you?', lowLabel: 'Forgettable', highLabel: 'Unforgettable', feels: { 0: 'Generic cardboard cutouts with unbelievable motivations.', 1: 'Hard to root for or differentiate between the secondary cast.', 2: 'Standard fantasy/sci-fi archetypes that serve their roles fine.', 3: 'Engaging, sympathetic leads with clear drives and dynamic relationships.', 4: 'Compelling character development and memorable, distinct voices.', 5: 'A fantastic, standout cast with great depth and memorable dynamics.' } },
    { id: 'PL', title: 'Plot & pacing', weight: 0.20, question: 'How well did the story move?', lowLabel: 'Dragged', highLabel: 'Gripping', feels: { 0: 'Bogged down in endless exposition and zero forward progress.', 1: 'Frequent pacing issues, spending too much time on mundane details.', 2: 'Steady journey with standard quest progression.', 3: 'Good balance of world-expanding exposition and action-packed narrative.', 4: 'High stakes and great momentum that kept the pages turning fast.', 5: 'Thrilling narrative executed with fantastic pacing and great twists.' } },
    { id: 'WR', title: 'Writing & prose', weight: 0.10, question: 'How was the sentence-level craft?', lowLabel: 'Clunky', highLabel: 'Quotable', feels: { 0: 'Overloaded with info-dumps and clunky, unnatural dialogue.', 1: 'Stilted phrasing that made immersive fantasy hard to believe.', 2: 'Clear and functional prose that gets the job done.', 3: 'Evocative writing that brings the fantastical elements to life.', 4: 'Atmospheric and polished prose filled with striking imagery.', 5: 'Atmospheric, standout writing that brought the world vividly to life.' } },
    { id: 'PY', title: 'Emotional payoff & ending', weight: 0.10, question: 'Was the ending satisfying and well-resolved?', lowLabel: 'Undid the build-up', highLabel: 'Perfect landing', feels: { 0: 'Deus ex machina nonsense that ruined the entire narrative conflict.', 1: 'Felt rushed, leaving too many critical plot threads dangling abruptly.', 2: 'Resolved the core conflict decently, if a bit predictably.', 3: 'Tying together character arcs and plot lines into a satisfying climax.', 4: 'Thrilling resolution that delivered on every single promise.', 5: 'A stellar ending that paid off every build-up beat brilliantly.' } },
    { id: 'EN', title: 'Overall enjoyment', weight: 0.15, question: 'How much did you enjoy reading it?', lowLabel: 'A chore', highLabel: "Couldn't put down", feels: { 0: 'Felt like a endless slog through dense, boring lore.', 1: 'Hard to stay focused; felt more like homework than entertainment.', 2: 'Decent entertainment if you enjoy the sub-genre.', 3: 'A fun escapist adventure that held my attention well.', 4: 'Extremely fun read; I was eager to get back to this world.', 5: 'An absolute blast to read; an instant new favorite.' } },
    { id: 'RC', title: 'Would you recommend it', weight: 0.10, question: 'Would you hand this to a friend?', choices: REC_OPTIONS },
  ]
};
