import { REC_OPTIONS } from './recOptions.js';

export const fiction = {
  label: 'General fiction',
  categories: [
    { id: 'CH', title: 'Characters', weight: 0.20, question: 'How did the characters land for you?', lowLabel: 'Forgettable', highLabel: 'Unforgettable', feels: { 0: 'Flat, irritating, or completely unconvincing character dynamics.', 1: 'Thinly written; I couldn’t find anyone to root for or connect with.', 2: 'Serviceable, but mostly functional archetypes rather than real people.', 3: 'Relatable and well-drawn enough to keep me engaged throughout.', 4: 'Vivid and layered; their decisions made sense and felt human.', 5: 'Remarkably nuanced characters who felt entirely real and stayed with me.' } },
    { id: 'WR', title: 'Writing & prose', weight: 0.15, question: 'How was the sentence-level craft?', lowLabel: 'Clunky', highLabel: 'Quotable', feels: { 0: 'Clunky, repetitive, or full of distracting errors and poor rhythm.', 1: 'Dry or awkward phrasing that regularly pulled me out of the story.', 2: 'Readable and plain, though lacking any distinct voice or elegance.', 3: 'Smooth and polished prose that comfortably carries the narrative.', 4: 'Beautifully crafted with memorable descriptions and strong cadence.', 5: 'Gorgeous, polished prose where every sentence lands smoothly.' } },
    { id: 'PL', title: 'Plot & pacing', weight: 0.20, question: 'How well did the story move?', lowLabel: 'Dragged', highLabel: 'Gripping', feels: { 0: 'Full of plot holes, aimless detours, or painfully sluggish narrative momentum.', 1: 'Pacing was noticeably uneven with long stretches where nothing happened.', 2: 'Follows a standard trajectory, though a few sections sagged.', 3: 'Paced well, keeping a steady dynamic rhythm from start to finish.', 4: 'Engrossing plot with well-timed reveals and great momentum.', 5: 'Completely engrossing; held my attention from start to finish.' } },
    { id: 'PY', title: 'Emotional payoff & ending', weight: 0.15, question: 'Was the ending satisfying and well-resolved?', lowLabel: 'Undid the build-up', highLabel: 'Perfect landing', feels: { 0: 'Frustrating, rushed, or fundamentally undid the entire build-up.', 1: 'Felt abrupt or left major character arcs unresolved and unsatisfying.', 2: 'A predictable or standard resolution that met minimum expectations.', 3: 'Satisfying ending that wrapped up the main emotional beats nicely.', 4: 'Resonated strongly, delivering a memorable and rewarding finish.', 5: 'An exceptional, deeply satisfying finish that landed perfectly.' } },
    { id: 'EN', title: 'Overall enjoyment', weight: 0.15, question: 'How much did you enjoy reading it?', lowLabel: 'A chore', highLabel: "Couldn't put down", feels: { 0: 'Reading this felt like a painful chore from start to finish.', 1: 'Struggled to stay interested; took genuine effort to finish.', 2: 'An okay pastime, but I wasn’t particularly eager to pick it up.', 3: 'A fun and engaging read that kept me happily occupied.', 4: 'Thoroughly enjoyed my time with this book and looked forward to reading it.', 5: 'Pure joy—a total page-turner that I couldn’t put down.' } },
    { id: 'RC', title: 'Would you recommend it', weight: 0.15, question: 'Would you hand this to a friend?', choices: REC_OPTIONS },
  ]
};
