import { REC_OPTIONS } from './recOptions.js';

export const horror = {
  label: 'Horror',
  categories: [
    { id: 'AT', title: 'Atmosphere & dread', weight: 0.20, question: 'How thick was the tension?', lowLabel: 'Never unsettled me', highLabel: "Couldn't look away", feels: { 0: 'Flat, dull atmosphere that never managed to evoke any mood.', 1: 'Weak ambiance; failed to build a sense of foreboding or creepiness.', 2: 'Decent uncanny vibes in a few scenes, but inconsistent tone.', 3: 'Effective, eerie atmosphere that built tension well.', 4: 'Thick, suffocating dread that made me feel constantly uneasy.', 5: 'Incredible atmosphere that built genuine dread from start to finish.' } },
    { id: 'SC', title: 'Scares & effectiveness', weight: 0.15, question: 'Did it actually get to you?', lowLabel: 'Toothless', highLabel: 'Genuinely rattled me', feels: { 0: 'Toothless and silly; cheap horror tricks that fell completely flat.', 1: 'Predictable frights that failed to generate real fear or shock.', 2: 'A few solid creepy imagery moments, but generally mild.', 3: 'Geniunely scary sequences that made my skin crawl.', 4: 'Deeply unsettling scares that lingered long after closing the book.', 5: 'Effectively scary and unsettling—delivered great genre thrills.' } },
    { id: 'CH', title: 'Characters', weight: 0.15, question: 'How did the characters land for you?', lowLabel: 'Forgettable', highLabel: 'Unforgettable', feels: { 0: 'Stupid character choices made only to serve monster fodder.', 1: 'Boring characters who were hard to care about when in danger.', 2: 'Standard horror cast; passable enough to root for their survival.', 3: 'Sympathetic cast whose safety I genuinely cared about.', 4: 'Complex, deeply human characters facing unimaginable terror.', 5: 'Easy to root for, grounded characters facing wild odds.' } },
    { id: 'WR', title: 'Writing & prose', weight: 0.10, question: 'How was the sentence-level craft?', lowLabel: 'Clunky', highLabel: 'Quotable', feels: { 0: 'Clunky descriptions that ruined any attempt at visceral horror.', 1: 'Repetitive wording that diminished scary moments.', 2: 'Straightforward writing that delivered horror beats plainly.', 3: 'Evocative prose that painted vivid, creepy pictures.', 4: 'Rich, gothic, or atmospheric prose that heightened horror elements.', 5: 'Visceral, atmospheric prose that set the creepy tone perfectly.' } },
    { id: 'PL', title: 'Plot & pacing', weight: 0.10, question: 'How well did the story move?', lowLabel: 'Dragged', highLabel: 'Gripping', feels: { 0: 'Painfully slow build-up with zero payoff or narrative energy.', 1: 'Dragging middle act that lost all built-up momentum.', 2: 'Steady horror pacing leading to a standard climax.', 3: 'Well-paced escalations that kept the pressure building high.', 4: 'Fast, relentless horror escalation that held me spellbound.', 5: 'Terrific pacing that escalated the threat smoothly to a big finish.' } },
    { id: 'EN', title: 'Overall enjoyment', weight: 0.15, question: 'How much did you enjoy reading it?', lowLabel: 'A chore', highLabel: "Couldn't put down", feels: { 0: 'A boring or offensive chore that gave zero horror thrill.', 1: 'Hard to finish; failed to hold my interest in the central threat.', 2: 'A fun spooky read for the Halloween season.', 3: 'Great thrill ride that delivered solid genre thrills.', 4: 'Compelling dark story that kept me reading late into night.', 5: 'A thrilling, wildly fun horror read that I devoured.' } },
    { id: 'RC', title: 'Would you recommend it', weight: 0.15, question: 'Would you hand this to a friend?', choices: REC_OPTIONS },
  ]
};
