import { REC_OPTIONS } from './recOptions.js';

export const mystery = {
  label: 'Mystery & thriller',
  categories: [
    { id: 'HK', title: 'Hook & suspense', weight: 0.18, question: 'How deeply did the psychological tension and setup pull you in?', lowLabel: 'Predictable & flat', highLabel: 'Unputdownable', feels: { 0: 'Flat and predictable with no real psychological tension.', 1: 'Weak hook that struggled to build genuine curiosity or suspense.', 2: 'Standard setup that kept me curious enough to turn pages.', 3: 'Solid psychological suspense with clever mind games and hooks.', 4: 'High-tension setup that kept me constantly second-guessing.', 5: 'Masterful suspense with an irresistible hook that kept me utterly obsessed.' } },
    { id: 'TN', title: 'Tension & pacing', weight: 0.18, question: 'How taut did it stay?', lowLabel: 'Slack', highLabel: 'Relentless', feels: { 0: 'Boring, sluggish, and completely devoid of suspense or urgency.', 1: 'Low tension that struggled to maintain excitement between reveals.', 2: 'Moderate suspense; enough to keep going, but lacked real edge.', 3: 'Taut and punchy with good cliffhangers at chapter ends.', 4: 'White-knuckle tension that kept me anxious in the best way.', 5: 'Edge-of-your-seat suspense that kept the pressure high throughout.' } },
    { id: 'TW', title: 'Twist & reveal', weight: 0.14, allowNA: true, question: 'How did the big reveal land?', lowLabel: 'Cheap or nonsensical', highLabel: 'Genuinely shocking', feels: { 0: 'Ridiculous, absurd, or completely shattered character logic for shock value.', 1: 'Predictable miles away or felt like a disappointment when revealed.', 2: 'A standard twist that worked okay even if it wasn’t mind-blowing.', 3: 'A clever reveal that caught me off guard and made sense.', 4: 'Surprising, highly satisfying, and recontextualized earlier events.', 5: 'Fantastic twist—surprising, clever, and made total sense in hindsight.' } },
    { id: 'CH', title: 'Characters', weight: 0.15, question: 'How did the characters land for you?', lowLabel: 'Forgettable', highLabel: 'Unforgettable', feels: { 0: 'Unbelievable motives, nonsensical decisions, and annoying cast.', 1: 'Generic detective/victim tropes with little emotional depth.', 2: 'Functional characters who moved the investigation along decently.', 3: 'Intriguing suspects and a compelling protagonist with real flaws.', 4: 'Richly motivated characters whose secrets drove the plot dynamic.', 5: 'Vivid, highly compelling characters with distinct, sharp motivations.' } },
    { id: 'WR', title: 'Writing & prose', weight: 0.10, question: 'How was the sentence-level craft?', lowLabel: 'Clunky', highLabel: 'Quotable', feels: { 0: 'Clunky exposition dump that killed all narrative momentum.', 1: 'Utilitarian prose that occasionally distracted with awkward phrasing.', 2: 'Clean, simple writing suited for a fast-paced mystery.', 3: 'Sharp, punchy prose that set a great noir or tense tone.', 4: 'Atmospheric writing that heightened every scene of suspense.', 5: 'Tight, sharp writing that kept the narrative moving briskly.' } },
    { id: 'EN', title: 'Overall enjoyment', weight: 0.15, question: 'How much did you enjoy reading it?', lowLabel: 'A chore', highLabel: "Couldn't put down", feels: { 0: 'Felt like dragging myself through a tedious police report.', 1: 'Hard to care about the outcome or who the culprit was.', 2: 'An enjoyable mystery, good for a quick distraction.', 3: 'Thoroughly entertaining puzzle that kept me guessing happily.', 4: 'Fast-paced, thrill ride that I devoured in just a couple sittings.', 5: 'A total page-turner that kept me guessing and hooked until the end.' } },
    { id: 'RC', title: 'Would you recommend it', weight: 0.10, question: 'Would you hand this to a friend?', choices: REC_OPTIONS },
  ]
};
