import { REC_OPTIONS } from './recOptions.js';

export const nonfiction = {
  label: 'Nonfiction',
  categories: [
    { id: 'AR', title: 'Argument & insight', weight: 0.20, question: 'How strong or original was the central idea?', lowLabel: 'Thin or obvious', highLabel: 'Changed my thinking', feels: { 0: 'Flawed thesis based on false premises or totally banalities.', 1: 'Thin argument that offered little new perspective or depth.', 2: 'Decent insights, though mostly repeating well-known ideas.', 3: 'Solid thesis backed by interesting perspectives and new ideas.', 4: 'Thought-provoking thesis that challenged my assumptions.', 5: 'Extremely insightful and well-argued; offered brilliant new ideas.' } },
    { id: 'RS', title: 'Research & rigor', weight: 0.15, question: 'How well-supported were the claims?', lowLabel: 'Shaky', highLabel: 'Airtight', feels: { 0: 'Shaky, cherry-picked facts with zero academic or journalistic rigor.', 1: 'Anecdotal evidence replacing real research or strong evidence.', 2: 'Adequately researched, though reliant on secondary sources.', 3: 'Well-supported with solid evidence, data, and citations.', 4: 'Rigorous and thorough research that bolstered every point.', 5: 'Thoroughly researched and exceptionally well-supported throughout.' } },
    { id: 'CL', title: 'Clarity & structure', weight: 0.15, question: 'How easy was it to follow?', lowLabel: 'Muddled', highLabel: 'Crystal clear', feels: { 0: 'Muddled, repetitive, and completely disorganized chapters.', 1: 'Confusing structure that often jumped wildly between topics.', 2: 'Follows a basic logic, though some chapters felt misplaced.', 3: 'Clear structure that guided me smoothly through the argument.', 4: 'Extremely well-organized, building logical momentum chapter to chapter.', 5: 'Crystal clear and logically organized—complex topics felt easy to follow.' } },
    { id: 'CH', title: 'Key figures & subjects', weight: 0.15, question: 'How compelling were the people or subjects covered?', lowLabel: 'Uninteresting', highLabel: 'Fascinating', feels: { 0: 'Dry, unrelatable subjects that failed to hold interest.', 1: 'Superficial treatment of the key figures involved.', 2: 'Decent overview of the subjects.', 3: 'Engaging, humanized depiction of key people and topics.', 4: 'Very compelling, layered portrayal of historical or real figures.', 5: 'Fascinating, deeply human focus that made the subject come alive.' } },
    { id: 'WR', title: 'Writing style', weight: 0.10, question: 'How was the sentence-level craft?', lowLabel: 'Dry, a slog', highLabel: 'A pleasure to read', feels: { 0: 'Dry, impenetrable jargon that made reading an absolute slog.', 1: 'Academic or bland writing style that made the topic feel boring.', 2: 'Clear, straightforward prose without much stylistic flair.', 3: 'Engaging, narrative-driven style that made facts enjoyable.', 4: 'Vivid and persuasive writing style that brought topics to life.', 5: 'Engaging, crisp writing that made the material a breeze to read.' } },
    { id: 'EN', title: 'Overall engagement', weight: 0.15, question: 'How readable was it, cover to cover?', lowLabel: 'A chore', highLabel: "Couldn't put down", feels: { 0: 'Felt like reading a dry textbook against my will.', 1: 'Hard to stay engaged; skimmable sections outweighed good ones.', 2: 'Interesting enough to finish if you care about the subject.', 3: 'Consistently engaging read from start to finish.', 4: 'Absorbing narrative that held my attention completely.', 5: 'Captivating read—kept me interested from start to finish.' } },
    { id: 'RC', title: 'Would you recommend it', weight: 0.10, question: 'Would you hand this to a friend?', choices: REC_OPTIONS },
  ]
};
