import { REC_OPTIONS } from './recOptions.js';

export const romance = {
  label: 'Romance',
  categories: [
    { id: 'CM', title: 'Chemistry', weight: 0.20, question: 'Did you believe the pull between them?', lowLabel: 'No spark', highLabel: 'Combustible', feels: { 0: 'Zero chemistry; interactions felt forced, toxic, or awkward.', 1: 'Lacked real spark; hard to see why these characters liked each other.', 2: 'Decent dynamic, though feeling more like friends than lovers.', 3: 'Clear spark and enjoyable banter between the romantic leads.', 4: 'Electric chemistry that made every shared scene dynamic.', 5: 'Fantastic spark and magnetic connection that carried every scene.' } },
    { id: 'CH', title: 'Characters', weight: 0.15, question: 'How did the leads land for you?', lowLabel: 'Forgettable', highLabel: 'Unforgettable', feels: { 0: 'Flat, annoying characters with zero depth.', 1: 'Hard to root for either lead in the relationship.', 2: 'Decent leads, but relied heavily on tropes.', 3: 'Likable characters with clear personal motivation.', 4: 'Layered, empathetic leads with great personal growth.', 5: 'Unforgettable, rich characters you care about deeply.' } },
    { id: 'TR', title: 'Trope execution', weight: 0.10, question: 'How well did it deliver on its tropes?', lowLabel: 'Phoned in', highLabel: 'Best-in-class', feels: { 0: 'Lazy, cliché-ridden execution that relied on ridiculous miscommunication.', 1: 'Phoned in; hit tropes on a checklist without adding fresh energy.', 2: 'Standard execution of genre tropes that satisfied basic expectations.', 3: 'Fun, refreshing twist on beloved tropes that landed well.', 4: 'Masterful spin on classic romance dynamics that felt vibrant.', 5: 'Outstanding spin on genre tropes—felt fresh and genuinely well-done.' } },
    { id: 'PY', title: 'Emotional payoff & ending', weight: 0.15, question: 'Was the ending satisfying and well-resolved?', lowLabel: 'Undid the build-up', highLabel: 'Perfect landing', feels: { 0: 'Ending felt completely unearned, rushed, or unconvincing.', 1: 'Weak resolution to emotional conflicts; third-act conflict felt forced.', 2: 'A predictable Happy Ever After that did its job.', 3: 'Warm, satisfying emotional resolution that left a big smile.', 4: 'Deeply moving climax that delivered a hugely rewarding payout.', 5: 'Swoon-worthy ending that paid off all the romantic tension wonderfully.' } },
    { id: 'WR', title: 'Writing & prose', weight: 0.08, question: 'How was the sentence-level craft?', lowLabel: 'Clunky', highLabel: 'Quotable', feels: { 0: 'Cringey dialogue and purple prose that ruined romantic moments.', 1: 'Basic prose with repetitive descriptions and awkward dialogue.', 2: 'Easy to read, simple prose that didn’t get in the way of the story.', 3: 'Charming, clever writing with snappy dialogue and great flow.', 4: 'Beautifully written romantic prose filled with memorable quotes.', 5: 'Witty, warm, and beautifully written with great banter throughout.' } },
    { id: 'PL', title: 'Plot & pacing', weight: 0.07, question: 'How well did the story move?', lowLabel: 'Dragged', highLabel: 'Gripping', feels: { 0: 'Plot dragged endlessly with useless subplots halting romance.', 1: 'Uneven pacing where romance ground to a halt for long periods.', 2: 'Pacing kept moving steadily through standard romance beats.', 3: 'Good balance between personal character growth and relationship plot.', 4: 'Engrossing narrative momentum that kept me deeply invested.', 5: 'Great pacing—kept me totally invested in the story and relationship.' } },
    { id: 'EN', title: 'Overall enjoyment', weight: 0.15, question: 'How much did you enjoy reading it?', lowLabel: 'A chore', highLabel: "Couldn't put down", feels: { 0: 'Felt like a chore to get through; zero emotional investment.', 1: 'A struggle to finish; didn’t care if they ended up together.', 2: 'A light, pleasant read for a rainy afternoon.', 3: 'Fun, heartwarming, and very engaging from start to finish.', 4: 'Delightful read that had me smiling and giggling continuously.', 5: 'An absolute delight to read; left me with a huge smile.' } },
    { id: 'RC', title: 'Would you recommend it', weight: 0.10, question: 'Would you hand this to a friend?', choices: REC_OPTIONS },
  ]
};
